Comments function
Hiroaki-Shimohira/proto_space pull request #12
Opened 2016-09-15 14:32 UTC by Hiroaki-Shimohira

# what
コメント機能
# why
コメントできるようにするため。

2016-09-15 14:35 UTC, hc070208 commented on app/views/prototypes/_comment.html.haml
> +        %img.media-object{alt: "64x64", "data-holder-rendered": "true", "data-src": "holder.js/64x64", src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9
ここユーザーの画像にしてほしいかな

2016-09-15 14:38 UTC, hc070208 commented on app/views/prototypes/_comment.html.haml
> +-@comments.each do |comment_data|
eachじゃなくてrenderにしたいね

2016-09-15 14:38 UTC, hc070208 commented on app/views/prototypes/show.html.haml
> +      = render 'comment'
ここのrenderはいらないかな

2016-09-15 14:39 UTC, hc0208 requested changes

2016-09-16 06:29 UTC, hc070208 commented on app/controllers/comments_controller.rb
> +		@comment = Comment.new
これいらないかな

2016-09-16 06:29 UTC, hc0208 requested changes

2016-09-16 15:56 UTC, DaikiInaba commented
hamlで=の後にスペース入っているものといないものがあるので統一しましょう

2016-09-16 16:09 UTC, ShuheiTsuji commented on app/views/comments/_comment.html.haml
> +      = comment.comment
改行だーーーーーーーーー

2016-09-16 16:10 UTC, ShuheiTsuji reviewed
test

2016-09-16 16:10 UTC, ShuheiTsuji commented on app/views/comments/_comment.html.haml
> +      =comment.comment
改行ない。。。。。。

2016-09-16 16:11 UTC, ShuheiTsuji commented
![LGTM](https://lgtm.in/p/8MaFkpZct)

2016-09-16 16:13 UTC, merged