User model test
Hiroaki-Shimohira/proto_space pull request #19
Opened 2016-10-08 08:32 UTC by Hiroaki-Shimohira

# what 
モデルのテスト
# why 
validationがしっかり機能するか確かめるため

2016-10-09 06:33 UTC, hc0208 requested changes

2016-10-09 06:33 UTC, hc070208 commented on spec/models/prototype_spec.rb
> +				prototype = create(:prototype)
prototype = create(:prototype)は複数あるからまとめたいね。

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/factories/capture_image.rb
> +end
改行

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/factories/prototype.rb
> +end
改行

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/factories/like.rb
> +end
改行

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/factories/user.rb
> +end
改行

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/capture_image_spec.rb
> +			binding.pry
　binding.pry消しておこう

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/factories/capture_image.rb
> +		satus "main_image"
ここでtraitなどを使用してあげると綺麗にコード書けるから一度書いてみよう😊

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/capture_image_spec.rb
> +end
改行

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/capture_image_spec.rb
> +end
アソシエーションのテスト書いた？

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/prototype_spec.rb
> +	before do
インデントがすごいきになるw

これは直しておこう

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/prototype_spec.rb
> +				expect{@prototype.destroy}.to change{Comment.count}.by(-1)
{ @prototype }みたいな形で1つ空白作ろう

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/prototype_spec.rb
> +				expect{@prototype.destroy}.to change{Like.count}.by(-1)
ここlikes_count 5個ぐらい作って、Like.countが5個減るか確認して欲しい。

create_listとかよく使うから確認してみて😊

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/prototype_spec.rb
> +				expect{@prototype.destroy}.to change{Comment.count}.by(-1)
ここも5個:likeと同様に5つぐらい確かめてみよう

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/prototype_spec.rb
> +end
userとのassociationも確認してもらいたい😊

2016-10-10 16:18 UTC, ShuheiTsuji commented on spec/models/user_spec.rb
> +		      user = create(:user)
インデントがきになるw

2016-10-10 16:22 UTC, Hiroaki-Shimohira commented on spec/factories/prototype.rb
> +end
done

2016-10-10 16:22 UTC, Hiroaki-Shimohira commented on spec/factories/like.rb
> +end
done

2016-10-10 16:22 UTC, Hiroaki-Shimohira commented on spec/factories/user.rb
> +end
done

2016-10-10 16:22 UTC, Hiroaki-Shimohira commented on spec/models/capture_image_spec.rb
> +			binding.pry
done

2016-10-10 16:23 UTC, Hiroaki-Shimohira commented on spec/models/prototype_spec.rb
> +				expect{@prototype.destroy}.to change{Comment.count}.by(-1)
done

2016-10-10 17:22 UTC, ShuheiTsuji commented on spec/factories/capture_image.rb
> +end
改行

2016-10-10 17:22 UTC, ShuheiTsuji commented on spec/models/prototype_spec.rb
> +				prototypes = create_list(:prototype, 3)
ここは1個で大丈夫

2016-10-10 17:40 UTC, ShuheiTsuji commented
https://lgtm.in/p/guVMDuWsn

2016-10-10 17:40 UTC, ShuheiTsuji commented
よっしゃ！

あともう少し！😊頑張っていこう！

2016-10-10 17:40 UTC, merged